#!/bin/sh
#
# runit haproxy
#

PID_PATH=/var/run/haproxy.pid
BIN_PATH=/usr/local/sbin/haproxy
CFG_PATH=/usr/local/etc/haproxy/haproxy.cfg

exec /bin/bash <<EOF
$BIN_PATH -f $CFG_PATH -D -p $PID_PATH

trap "$BIN_PATH -f $CFG_PATH -D -p $PID_PATH -sf \\\$(cat $PID_PATH)" SIGHUP
trap "kill -TERM \\\$(cat $PID_PATH) && exit 0" SIGTERM SIGINT

while true; do # Iterate to keep job running.
  sleep 1 # Wake up to handle signals
  kill -0 $(cat $PID_PATH) || exit 1 # exit if haproxy is totally done for
done
EOF
